# Generated by Django 5.2.6 on 2025-11-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlysignup',
            name='gdpr_consent',
            field=models.BooleanField(default=False),
        ),
    ]
